apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: wps
        image: regfork8s.azurecr.io/wordpress:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: WORDPRESS_DB_HOST
          value: ${DB_HOST}
        - name: WORDPRESS_DB_NAME
          value: ${DB_NAME}
        - name: WORDPRESS_DB_USER
          value: ${DB_USER}
        - name: WORDPRESS_DB_PASSWORD
          value: ${DB_PASSWORD}
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front